-- MySQL Script generated by MySQL Workbench
-- Sat Jun 11 17:34:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `dw_dm_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw_dm_cliente` ;

CREATE TABLE IF NOT EXISTS `dw_dm_cliente` (
  `sk_dm_cliente` INT NULL,
  `nome_cliente` VARCHAR(45) NULL,
  `cpf_cliente` VARCHAR(45) NULL,
  `data_nasc` DATE NULL,
  `faixa_rating_cliente` VARCHAR(45) NULL,
  `faixa_renda_familiar` VARCHAR(45) NULL,
  `valor_limite_credito` FLOAT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_dm_conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw_dm_conta` ;

CREATE TABLE IF NOT EXISTS `dw_dm_conta` (
  `sk_dm_conta` INT NULL,
  `nro_conta` VARCHAR(10) NULL,
  `nro_agencia` INT NULL,
  `nome_banco` VARCHAR(60) NULL,
  `nro_banco` INT NULL,
  `tipo_conta` VARCHAR(45) NULL,
  `data_abertura` DATE NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_dm_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw_dm_data` ;

CREATE TABLE IF NOT EXISTS `dw_dm_data` (
  `sk_dm_data` INT NULL,
  `dia` DATE NULL,
  `mes` INT NULL,
  `semestre` INT NULL,
  `trimestre` INT NULL,
  `ano` INT NULL,
  `feriado` TINYINT NULL,
  `dia_util` TINYINT NULL,
  `dia_semana` VARCHAR(20) NULL,
  `quinto_dia_util` TINYINT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_dm_localidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw_dm_localidade` ;

CREATE TABLE IF NOT EXISTS `dw_dm_localidade` (
  `sk_dm_localidade` INT NULL,
  `cep` VARCHAR(9) NULL,
  `latitude` VARCHAR(15) NULL,
  `longitude` VARCHAR(15) NULL,
  `endereco` VARCHAR(100) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(100) NULL,
  `estado` VARCHAR(45) NULL,
  `regiao` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_dm_produto_credito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw_dm_produto_credito` ;

CREATE TABLE IF NOT EXISTS `dw_dm_produto_credito` (
  `sk_dm_produto_credito` INT NULL,
  `desc_prod_credito` VARCHAR(100) NULL,
  `cod_prod_credito` VARCHAR(10) NULL,
  `categoria_prod_credito` VARCHAR(45) NULL,
  `prazo` INT NULL,
  `faixa_juros` VARCHAR(45) NULL,
  `faixa_valores` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_dm_produto_investimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw_dm_produto_investimento` ;

CREATE TABLE IF NOT EXISTS `dw_dm_produto_investimento` (
  `sk_dm_produto_investimento` INT NULL,
  `desc_prod_invest` VARCHAR(100) NULL,
  `cod_prod_invest` VARCHAR(20) NULL,
  `cat_prod_invest` VARCHAR(20) NULL,
  `prazo_liquidez` INT NULL,
  `categoria_risco` VARCHAR(45) NULL,
  `tipo_invest` VARCHAR(45) NULL,
  `faxa_valor_incial` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_dm_tipo_transacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw_dm_tipo_transacao` ;

CREATE TABLE IF NOT EXISTS `dw_dm_tipo_transacao` (
  `sk_dm_tipo_transacao` INT NULL,
  `desc_tipo_transacao` VARCHAR(45) NULL,
  `cod_tipo_transacao` VARCHAR(10) NULL,
  `categoria_tipo_transacao` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_ft_contratacao_credito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw_ft_contratacao_credito` ;

CREATE TABLE IF NOT EXISTS `dw_ft_contratacao_credito` (
  `sk_dm_prod_credito` INT NULL,
  `sk_dm_cliente` INT NULL,
  `sk_dm_data` INT NULL,
  `sk_dm_localidade` INT NULL,
  `valor_total_contratacao` FLOAT NULL,
  `qtd_prod_credito` INT NULL,
  `valor_total_juros` FLOAT NULL,
  `perc_juros` FLOAT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_ft_contratacao_investimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw_ft_contratacao_investimento` ;

CREATE TABLE IF NOT EXISTS `dw_ft_contratacao_investimento` (
  `sk_dm_prod_investimento` INT NULL,
  `sk_dm_cliente` INT NULL,
  `sk_dm_data` INT NULL,
  `sk_dm_localidade` INT NULL,
  `valor_total_investimento` FLOAT NULL,
  `qtde_prod_investimento` INT NULL,
  `valor_taxas_adm` FLOAT NULL,
  `valor_total_tributos` FLOAT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_ft_liquidacao_credito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw_ft_liquidacao_credito` ;

CREATE TABLE IF NOT EXISTS `dw_ft_liquidacao_credito` (
  `sk_dm_prod_credito` INT NULL,
  `sk_dm_cliente` INT NULL,
  `sk_dm_data` INT NULL,
  `sk_dm_localidade` INT NULL,
  `valor_total_liquidacao` FLOAT NULL,
  `qtd_prod_credito_liquidacao` INT NULL,
  `valor_total_amortizado` FLOAT NULL,
  `prazo_amortizado` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_ft_liquidacao_investimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw_ft_liquidacao_investimento` ;

CREATE TABLE IF NOT EXISTS `dw_ft_liquidacao_investimento` (
  `sk_dm_prod_investimento` INT NULL,
  `sk_dm_cliente` INT NULL,
  `sk_dm_data` INT NULL,
  `sk_dm_localidade` INT NULL,
  `valor_total_liq_investimento` FLOAT NULL,
  `qtde_prod_liq_investimento` INT NULL,
  `valor_total_rentabilidade` FLOAT NULL,
  `valor_total_taxas` FLOAT NULL,
  `valor_total_impostos` FLOAT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_ft_transacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw_ft_transacao` ;

CREATE TABLE IF NOT EXISTS `dw_ft_transacao` (
  `sk_dm_cliente` INT NULL,
  `sk_dm_data` INT NULL,
  `sk_dm_tipo_transacao` INT NULL,
  `sk_dm_conta` INT NULL,
  `sk_dm_localidade` INT NULL,
  `valor_transacao` FLOAT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
